### ISSUE TITLE
A question from a python novice

### ISSUE THREAD

**Issue by WhiteSheep250** [AKASH2907/indian_landmark_recognition#1]
I'm interested in this method. But I have a little question that how to use your programs, and what is the order of using of files. Thanks.
By the way, Can I experiment with my own image?

**Comment by AKASH2907** [comment]
It should work on your personal images too. Make sure image resolutions are not that large, because then, you have to set the threshold for Objectness Trained Model, that detects the salient regions in the image.

So, firstly, you run saliency.py that will use ObjectnessTrainedModel to generate salient regions from an image. Using that, you can increase the number of images in your training dataset. It also helps to get the local information along with the global information. 

gen_array.py and modify_data.py is to modify the data and mark them in serial orders plus create a batch of training data.

inception_v3_finetuning and inception_resnet_v2_finetuning are the models that were finetuned on the dataset.

In my case, inception_resent_v2 performed better than inception V3, therfore I used the saved weights of this model to predicts the class of monuments using the file new_model.py
